Basic Link Handling
icyphox/taigobot pull request #4
Opened 2021-11-17 10:54 UTC by nojusr

2021-11-17 13:42 UTC, icyphox requested changes

2021-11-17 13:42 UTC, icyphox commented on plugins/link-handler.go
> +		}
bruh

2021-11-17 13:42 UTC, icyphox commented on plugins/link-handler.go
> +			output += getDescriptionFromURL(value)
probably use `strings.Builder` for this? or `fmt.Sprintf` works too.

2021-11-17 13:42 UTC, icyphox commented on plugins/plugins.go
> +		if strings.HasPrefix(m.Trailing(), trigger) || trigger == "" {
is there a better way to do this?

2021-11-17 13:58 UTC, icyphox requested changes

2021-11-17 13:58 UTC, icyphox commented on plugins/link-handler.go
> +	}
pass the error up the stack.

2021-11-19 12:21 UTC, adedomin commented on plugins/plugins.go
> +		if strings.HasPrefix(m.Trailing(), trigger) || trigger == "" {
```
gore> :import "strings"
gore> strings.HasPrefix("fdsafdsafdsafdsa", "")
true
```
why the || trigger == "" ?

2021-11-21 15:41 UTC, merged